# Generated by Django 3.0.14 on 2022-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FilePathField(allow_folders=True, default='./FileBase/aaa.bmp'),
        ),
    ]
