# Generated by Django 3.0.14 on 2021-12-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingproject',
            unique_together=set(),
        ),
    ]
