# Generated by Django 3.0.14 on 2022-01-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
