# Generated by Django 3.0.14 on 2022-01-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
    ]
