# Generated by Django 3.0.14 on 2022-01-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220111_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FilePathField(default='./FileBase/aaa.bmp'),
        ),
    ]
