# Generated by Django 3.0.14 on 2021-12-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211219_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='averageRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
