# Generated by Django 3.0.14 on 2022-01-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220102_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
