# Generated by Django 3.0.14 on 2021-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211219_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='averageRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='projects',
            name='folder',
            field=models.FilePathField(allow_folders=True, path='./'),
        ),
    ]
