# Generated by Django 3.0.14 on 2022-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220111_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='./FileBase/aaa.bmp', max_length=100),
        ),
    ]
