# Generated by Django 3.0.14 on 2021-12-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211221_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingproject',
            unique_together={('idProject', 'idUser')},
        ),
    ]
