# Generated by Django 3.0.14 on 2022-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_applications_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='folder',
            field=models.FilePathField(allow_folders=True, path='./frontend/public/FileBase/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='presentation',
            field=models.FilePathField(allow_folders=True, path='./frontend/public/FileBase/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='./frontend/public/FileBase/aaa.bmp', max_length=100),
        ),
    ]
