# Generated by Django 3.0.14 on 2022-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220126_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, max_length=855, null=True),
        ),
    ]
