# Generated by Django 3.0.14 on 2022-01-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='idRole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Roles'),
        ),
    ]
