# Generated by Django 3.0.14 on 2022-01-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_idrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='idRole',
        ),
    ]
