# Generated by Django 3.0.14 on 2022-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220126_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsdeveloper',
            old_name='Grapghic3D',
            new_name='Graphic3D',
        ),
    ]
