# Generated by Django 3.0.14 on 2022-01-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_users_idrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='idRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Roles'),
        ),
    ]
