version: "3.9"
   
services:
  backend:
    build: backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - 8000:8000 
    container_name: Backend_DJ

  frontend:
    build: frontend/
    ports:
     - 8080:80
   

networks:
  default:
      name: www






