# Generated by Django 3.0.14 on 2021-12-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('standarduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProjectSite.StandardUser')),
            ],
            options={
                'verbose_name': 'Deweloper',
                'verbose_name_plural': 'Deweloperzy',
            },
            bases=('ProjectSite.standarduser',),
        ),
    ]
