# Generated by Django 3.0.14 on 2021-12-18 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0003_remove_standarduser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
