# Generated by Django 3.0.14 on 2021-12-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0004_standarduser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='created_at',
        ),
    ]
