# Generated by Django 3.0.14 on 2022-01-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220126_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Assembler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Grapghic2DRaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Grapghic2DVector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Grapghic3D',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Other',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='SQL',
            field=models.BooleanField(default=False),
        ),
    ]
