# Generated by Django 3.0.14 on 2022-01-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220126_0444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboratorsproject',
            unique_together={('idProject', 'idUser')},
        ),
    ]
