# Generated by Django 3.0.14 on 2022-01-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220126_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsdeveloper',
            old_name='Grapghic2DRaster',
            new_name='Graphic2DRaster',
        ),
        migrations.RenameField(
            model_name='skillsdeveloper',
            old_name='Grapghic2DVector',
            new_name='Graphic2DVector',
        ),
    ]
