# Generated by Django 3.0.14 on 2023-03-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Assembler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Graphic2DRaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Graphic2DVector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Graphic3D',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Other',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='Python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsdeveloper',
            name='SQL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='idOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='./frontend/public/FileBase/defaulAvatar.bmp', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, max_length=855, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorsproject',
            unique_together={('idProject', 'idUser')},
        ),
    ]
